version: "3"
services:
  proxy:
    image: traefik:2.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8080:8080
      - 80:80
    command:
      - --api.insecure=true
      - --providers.docker.defaultrule=Host(`{{ normalize .Name }}.localhost`)
  api:
    build: .
    volumes:
      - ./api:/usr/local/src
    ports:
      - 3000
    environment:
      PORT: 3000
    command: npm run-script start
  client:
    build: .
    volumes:
      - ./client:/usr/local/src
    ports:
      - 3000
    environment:
      REACT_APP_API_URL: ws://api-planning-poker.localhost
      WDS_SOCKET_PORT: 80
    command: npm run-script start
